<?php

namespace FiThnitekBundle\Repository;

/**
 * ConvertirpointsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConvertirpointsRepository extends \Doctrine\ORM\EntityRepository
{
}
