<?php

namespace FiThnitekBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function envoyerParDestinataire()
    {
        $qb =$this->getEntityManager()
            ->createQuery("select c from FiThnitekBundle:Event c where c.titre='event'");
        return $query=$qb->getResult();

    }
}
