<?php

namespace FiThnitekBundle\Repository;

/**
 * NotificationEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationEventRepository extends \Doctrine\ORM\EntityRepository
{
}
