<?php

namespace FiThnitekBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{public function count1($idu,$type)
{

    $qb = $this->getEntityManager()->createQuery("select e from FiThnitekBundle:Notification e  where e.type='$type'and  e.seen=0 and e.iduser ='$idu'  ");
    return $query = $qb->getResult() ;
}
    public function count($idu)
    {

        $qb = $this->getEntityManager()->createQuery("select e from FiThnitekBundle:Notification e  where  e.seen=0 and e.iduser ='$idu'  ");
        return $query = $qb->getResult() ;
    }

    public function supp($idu,$article)
    {

        $qb = $this->getEntityManager()->createQuery(" DELETE from FiThnitekBundle:Notification e  where e.idarticle='$article' and e.iduser ='$idu'  ");
        return $query = $qb->getResult() ;
    }

    public function trie($idu,$t)
    {

        $qb = $this->getEntityManager()->createQuery("select e from FiThnitekBundle:Notification e  where  e.seen=0 and e.iduser ='$idu' and e.title='$t' ");
        return $query = $qb->getResult() ;
    }
    public function trieb($t)
    {

        $qb = $this->getEntityManager()->createQuery("select e from FiThnitekBundle:Notification e  where  e.seen=0 and e.type='$t' ");
        return $query = $qb->getResult() ;
    }
    public function trief($t,$idu)
    {

        $qb = $this->getEntityManager()->createQuery("select e from FiThnitekBundle:Notification e  where  e.seen=0 and e.type='$t' and e.iduser ='$idu' ");
        return $query = $qb->getResult() ;
    }
}
