<?php

namespace FiThnitekBundle\Repository;

/**
 * ParticipeEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipeEventRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindby($iduser,$idevent)
    {
        $qb =$this->getEntityManager()
            ->createQuery("select u from FiThnitekBundle:ParticipeEvent u where u.userid = :iduser and u.eventid = :idevent ")
            ->setParameters(array('iduser'=>$iduser,'idevent'=>$idevent));
        return $query=$qb->getResult();

    }

}
