user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

fi_thnitek:
    resource: "@FiThnitekBundle/Resources/config/routing.yml"
    prefix:   /FiThnitek

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

