# app/config/security.yml
security:
    encoders:
       FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_CLIENT:      ROLE_CLIENT
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_CHAUFFEUR:   ROLE_CHAUFFEUR


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                use_forward: false
                always_use_default_target_path: false
                default_target_path: /
                    # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true

    access_control:
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/, role: ROLE_ADMIN }
            - { path: ^/chauffeur/, role: ROLE_CHAUFFEUR }
            - { path: ^/client/, role: ROLE_CLIENT }
