fi_thnitek_homepage:
    path:     /
    defaults: { _controller: FiThnitekBundle:Default:index }
fi_thnitek_Back:
  path:     /back
  defaults: { _controller: FiThnitekBundle:Default:back }
fi_thnitek_login:
    path:     /login
    defaults: { _controller: FiThnitekBundle:Default:login }
fi_thnitek_register:
    path:     /Register
    defaults: { _controller: FiThnitekBundle:Default:Register }
Taxi:
  resource: "@FiThnitekBundle/Resources/config/routingTaxi.yml"
  prefix: /Taxi


