#############################Front#################################
fi_thnitek_login:
    path:     /login
    defaults: { _controller: FiThnitekBundle:Default:login }
fi_thnitek_OffreColis:
    path:     /OffreColis
    defaults: { _controller: FiThnitekBundle:Default:OffreColis }
fi_thnitek_CreateOffre:
    path:     /CreateOffre
    defaults: { _controller: FiThnitekBundle:OffreColis:ajouteroffrecolis }
fi_thnitek_afficherOffre:
    path:     /afficherOffre
    defaults: { _controller: FiThnitekBundle:OffreColis:afficherOffre }
fi_thnitek_supprimerOffre:
    path:     /supprimerOffre/{id}
    defaults: { _controller: FiThnitekBundle:OffreColis:supprimerOffre }
fi_thnitek_ModifierOffre:
    path:     /modifierOffre/{id}
    defaults: { _controller: FiThnitekBundle:OffreColis:ModifierOffre }
fi_thnitek_afficherall:
    path:     /afficherall
    defaults: { _controller: FiThnitekBundle:OffreColis:afficherall }
fi_thnitek_ajouterReservation:
    path:     /ajouterReservation/{id}
    defaults: { _controller: FiThnitekBundle:OffreColis:ajouterReservation }
fi_thnitek_affichageReservation:
    path:     /affichageReservation
    defaults: { _controller: FiThnitekBundle:OffreColis:afficherReserver }
fi_thnitek_supprimerReservation:
    path:     /supprimerReservation/{id}
    defaults: { _controller: FiThnitekBundle:OffreColis:supprimerReserver }
###############################Back################################################
fi_thnitek_afficherOffreback:
    path:     /afficherOffreback
    defaults: { _controller: FiThnitekBundle:OffreColis:afficherOffreback }
fi_thnitek_ajouterOffreback:
    path:     /ajouterOffreback
    defaults: { _controller: FiThnitekBundle:OffreColis:ajouteroffrecolisback }
fi_thnitek_supprimerOffreback:
    path:     /supprimerOffreback/{id}
    defaults: { _controller: FiThnitekBundle:OffreColis:supprimerOffreback }
fi_thnitek_ModifierOffreback:
    path:     /modifierOffreback/{id}
    defaults: { _controller: FiThnitekBundle:OffreColis:ModifierOffreback }
fi_thnitek_ajouterReservationback:
    path:     /ajouterReservationback/{id}
    defaults: { _controller: FiThnitekBundle:OffreColis:ajouterReservationback }
fi_thnitek_affichageReservationback:
    path:     /affichageReservationback
    defaults: { _controller: FiThnitekBundle:OffreColis:afficherReserverback }
fi_thnitek_supprimerReservationback:
    path:     /supprimerReservationback/{id}
    defaults: { _controller: FiThnitekBundle:OffreColis:supprimerReserverback }
fi_thnitek_AffichageDateColi:
    path:     /rechercheDateColi
    defaults: { _controller: FiThnitekBundle:OffreColis:rechercheDate }