fi_thnitek_homepage:
    path:     /
    defaults: { _controller: FiThnitekBundle:Default:index }




fi_thnitek_ajouterEvent:
    path:     /event/ajouterEvent
    defaults: { _controller: FiThnitekBundle:Event:ajouterEvent}
fi_thnitek_readEvent:
    path:     /event/read
    defaults: { _controller: FiThnitekBundle:Event:read}
fi_thnitek_deleteEvent:
    path:     /event/delete/{id}
    defaults: { _controller: FiThnitekBundle:Event:delete}
fi_thnitek_updateEvent:
    path:     /event/update/{id}
    defaults: { _controller: FiThnitekBundle:Event:update}

fi_thnitek_readques:
    path:     /questionnaire/read
    defaults: { _controller: FiThnitekBundle:Questionnaire:read}


fi_thnitek_deleteQuest:
    path:     /questionnaire/delete/{id}
    defaults: { _controller: FiThnitekBundle:Questionnaire:delete}
fi_thnitek_updateQuest:
    path:     /questionnaire/update/{id}
    defaults: { _controller: FiThnitekBundle:Questionnaire:update}
fi_thnitek_readoneevent:
    path:     /event/readone/{id}
    defaults: { _controller: FiThnitekBundle:Event:readOne}

fi_thnitek_ajouterques2:
  path:     /questionnaire/ajouterQuestionnaire2/{id}
  defaults: { _controller: FiThnitekBundle:Questionnaire:create}

fi_thnitek_readonequest:
      path:     /questionnaire/readone/{id}
      defaults: { _controller: FiThnitekBundle:Questionnaire:readOne}

fi_thnitek_participation:
    path:     /event/participer/{id}
    defaults: { _controller: FiThnitekBundle:Event:participer}

fi_thnitek_repondre:
    path:     /event/repondre/{id}
    defaults: { _controller: FiThnitekBundle:Event:repondre}

fi_thnitek_profile:
  path:     /event/profile
  defaults: { _controller: FiThnitekBundle:Profile:index}
fi_thnitek_activerEvent:
  path:     /event/activer/{id}
  defaults: { _controller: FiThnitekBundle:Event:activer}

fi_thnitek_desactiverEvent:
  path:     /event/desactiver/{id}
  defaults: { _controller: FiThnitekBundle:Event:desactiver}

fi_thnitek_AfficheNonRepondu:
  path:     /event/afficherEvent/{id}
  defaults: { _controller: FiThnitekBundle:Event:AfficherNonRepondu}

fi_thnitek_converssion:
  path:     /converssion
  defaults: { _controller: FiThnitekBundle:Profile:Converssion}

fi_thnitek_readNoPart2:
  path:     /events/read2
  defaults: { _controller: FiThnitekBundle:Notification:readNoPart}
fi_thnitek_readNoPart:
  path:     /events/read
  defaults: { _controller: FiThnitekBundle:NotificationEvent:readNoPart}